#!/usr/bin/env python3
import csv
import math
import sys
# A helper function to compute the distance between two points
# given their latitude and longitude.
def haversine(lat1, lon1, lat2, lon2):
   R = 6371 # Radius of the earth in km
   dLat = math.radians(lat2 - lat1)
   dLon = math.radians(lon2 - lon1)
   a = math.sin(dLat/2) * math.sin(dLat/2) + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dLon/2) * math.sin(dLon/2)
   c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
   d = R * c # Distance in km
   return d
# A helper function to get the frequencies of each tree species
# in each borough.
def get_frequencies(trees, boroughs):
   frequencies = {
       'NYC': 0,
       'Manhattan': 0,
       'Bronx': 0,
       'Brooklyn': 0,
       'Queens': 0,
       'Staten Island': 0
   }
   for tree in trees:
       frequencies['NYC'] += 1
       if tree['Borough'] in boroughs:
           frequencies[tree['Borough']] += 1
   return frequencies
# A helper function to get the total number of trees in each borough.
def get_total_trees(trees):
   totals = {
       'NYC': 0,
       'Manhattan': 0,
       'Bronx': 0,
       'Brooklyn': 0,
       'Queens': 0,
       'Staten Island': 0
   }
   for tree in trees:
       totals['NYC'] += 1
       if tree['Borough'] in totals:
           totals[tree['Borough']] += 1
   return totals
# A helper function to get the zip codes in which a certain tree species can be found.
def get_zip_codes(trees):
   zip_codes = []
   for tree in trees:
       if tree['zip_code'] not in zip_codes:
           zip_codes.append(tree['zip_code'])
   return zip_codes
# A helper function to get the average diameter of a certain tree species.
def get_average_diameter(trees):
   total_diameter = 0
   for tree in trees:
       total_diameter += float(tree['diameter'])
   return total_diameter / len(trees)
# A helper function to get the borough containing the largest number of a certain tree species.
def get_largest_borough(frequencies):
   largest_borough = None
   largest_freq = 0
   for borough in frequencies:
       if frequencies[borough] > largest_freq:
           largest_freq = frequencies[borough]
           largest_borough = borough
   return (largest_borough, largest_freq)
# A helper function to get the tree species that match the user's input.
def get_matching_species(trees, name):
   matching_trees = []
   for tree in trees:
       if name.lower() in tree['common_name'].lower():
           matching_trees.append(tree)
   return matching_trees
# A helper function to get all trees within a certain distance from a certain location.
def get_nearby_trees(trees, lat, lon, dist):
   nearby_trees = []
   for tree in trees:
       if haversine(float(tree['latitude']), float(tree['longitude']), lat, lon) <= dist:
           nearby_trees.append(tree)
   return nearby_trees
# A helper function to get the unique tree species within a certain distance from a certain location.
def get_unique_nearby_trees(trees):
   unique_trees = []
   for tree in trees:
       if tree['common_name'] not in unique_trees:
           unique_trees.append(tree['common_name'])
   return unique_trees
# A helper function to get the frequency of each tree species within a certain distance from a certain location.
def get_nearby_frequencies(trees):
   frequencies = {}
   for tree in trees:
       if tree['common_name'] in frequencies:
           frequencies[tree['common_name']] += 1
       else:
           frequencies[tree['common_name']] = 1
   return frequencies
# Main function.
def main():
   # File name should be the first and only argument.
   filename = sys.argv[1]
   # Read the data from the CSV file.
   trees = []
   with open(filename) as csv_file:
       csv_reader = csv.DictReader(csv_file)
       for row in csv_reader:
           trees.append(row)
   # Welcome message.
   print('Welcome to the treequery program.')
   print('To begin, try typing \'help\' for the list of valid commands.')
   # Interactive loop.
   while True:
       command = input('\nEnter a command: ')
       # Help command.
       if command == 'help':
           print('\nThe valid commands are as follows:')
           print('listtrees - Get a list of common tree names')
           print('treeinfo <tree_species_name> - Get information about a species of tree')
           print('nearby <latitude> <longitude> <distance> - Get a list of information of all trees within a defined distance from some location')
           print('help - Get a help page about each command')
           print('quit - Quit the application')
       # List trees command.
       elif command == 'listtrees':
           unique_trees = []
           for tree in trees:
               if tree['common_name'] not in unique_trees:
                   unique_trees.append(tree['common_name'])
           unique_trees.sort()
           print('\n' + '\n'.join(unique_trees) + '\n')
       # Tree info command.
       elif command.startswith('treeinfo'):
           name = command.split(' ')[1]
           matching_trees = get_matching_species(trees, name)
           if len(matching_trees) > 0:
               total_num = len(matching_trees)
               zip_codes = get_zip_codes(matching_trees)
               boroughs = get_largest_borough(get_frequencies(matching_trees, boroughs))
               avg_diameter = get_average_diameter(matching_trees)
               print('\nEntry: ' + name)
               print('Total number of such trees: ' + str(total_num))
               print('Zip codes in which this tree is found: ' + ', '.join(zip_codes))
               print('Borough containing the largest number of such trees: ' + boroughs[0] + ', with ' + str(boroughs[1]))
               print('Average diameter: %.2f' % avg_diameter + '\n')
           else:
               print('\nNo matching species found.\n')
       # Nearby command.
       elif command.startswith('nearby'):
           args = command.split(' ')
           if len(args) == 4:
               lat = float(args[1])
               lon = float(args[2])
               dist = float(args[3])
               nearby_trees = get_nearby_trees(trees, lat, lon, dist)
               if len(nearby_trees) > 0:
                   unique_trees = get_unique_nearby_trees(nearby_trees)
                   frequencies = get_nearby_frequencies(nearby_trees)
                   total_trees = get_total_trees(trees)
                   for tree in unique_trees:
                       freq = (frequencies[tree] / total_trees['NYC']) * 100
                       print('\n' + tree + ': ' + '%.2f' % freq + '%')
               else:
                   print('\nNo trees are present within this distance.\n')
           else:
               print('\nPlease enter the required arguments to use the nearby command. Use the \'help\' command to learn more details.\n')
       # Quit command.
       elif command == 'quit':
           print('\nGoodbye!\n')
           break
       # Invalid command.
       else:
           print('\nInvalid command. Please try again.\n')
if __name__ == '__main__':
   main()
